server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    #是否将自己注册到eureka-server 默认为true
    registerWithEureka: false
    #是否从eureka-server获取注册信息，默认为true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
